// react/react_blog/src/component/header.tsx
import React from 'react';
import "./header.css";
function Header() {
    return (
      <div>
            <header className="site-header">
                <div className="logo-and-tagline">
                    <a href="./" className="logo">
                    </a>
                    <a className="sr-only" href="./">Alen_Andry Blog</a>
                </div>
                <div>
            <li
            className="main-nav-search">
            <input
                            type="search"
                            className="search"
                name="username"/>
            <a href="./search?q={{ search }}" className="jetpack-search-filter__link">
                <svg
                width="32"
                height="32"
                viewBox="0 0 32 32"
                fill="#ff894e"
                xmlns="http://www.w3.org/2000/svg"
                >
                <path
                    d="M15.0726 10.4326C12.4801 10.4326 10.4 12.5451 10.4 15.1053C10.4 17.6978 12.5125 19.7779 15.0726 19.7779C17.6651 19.7779 19.7453 17.6654 19.7453 15.1053C19.744 12.544 17.664 10.4326 15.0726 10.4326Z"
                ></path>
                <path
                    d="M16.0327 0.447479C7.42401 0.447479 0.447693 7.4238 0.447693 16.0324C0.447693 24.6398 7.42401 31.6161 16.0314 31.6161C24.64 31.6161 31.6163 24.6398 31.6163 16.0324C31.6163 7.4238 24.64 0.447479 16.0327 0.447479ZM23.6163 24.0324C23.3926 24.2562 23.0401 24.385 22.6563 24.385C22.2726 24.385 21.9526 24.2575 21.6963 24.0324L18.7526 21.0887L18.4651 21.2487C17.4088 21.825 16.2576 22.145 15.0724 22.145C11.1998 22.145 8.06509 19.0087 8.06509 15.1376C8.06509 11.265 11.2013 8.13023 15.0724 8.13023C18.9451 8.13023 22.0798 11.2665 22.0798 15.1376C22.0798 16.5138 21.6961 17.8251 20.9273 18.9776L20.7348 19.2976L23.6473 22.2101C23.8711 22.4664 24.0311 22.7864 24.0311 23.1376C23.9998 23.4563 23.8723 23.7763 23.616 24.0326L23.6163 24.0324Z"
                ></path>
                </svg>
            </a>
            </li>
        </div>
        </header>
            <nav id="main-nav" className="main-nav mobile-is-closed">
                <ul>
                    <li className="main-nav-episodes"><a href="./rust">Rust Series</a></li>
                    <li className="main-nav-series"><a href="./backend">Backend Series</a></li>
                    <li className="main-nav-advertising">
                    <a href="./fontend_ml">Frontend ML Series</a>
                    </li>
                    <li className="main-nav-ask"><a href="./javascript">javascript Series</a></li>
                    <li className="main-nav-topics"><a href="./python">python Series</a></li>
                    <li className="main-nav-topics"><a href="./java">Java Series</a></li>
                    <li className="main-nav-ask"><a href="./vue">Vue Series</a></li>
                    <li className="main-nav-ask"><a href="./react">React Series</a></li>
                    <li className="main-nav-ask"><a href="./angular">Angular Series</a></li>
                    <li className="main-nav-ask"><a href="./git">Git Series</a></li>
                    <li className="main-nav-ask"><a href="./bash">Bash Series</a></li>
                    <li className="main-nav-ask"><a href="./data_structure">Data Structure</a></li>
                </ul>
            </nav>
            </div>
     
  );
}

export default Header;

// angular/blogangular/src/app/components/header/header.component.ts
import { Component, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { Location } from '@angular/common';
import { DataService } from 'src/app/service/data.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  constructor(private router: Router, private location: Location, private dataService: DataService) { }
  search: string = '';
  showHeader = true;

  onChangeEvent(event: any) {
    console.log(event.target.value);
    this.router.navigateByUrl('/search?q=' + this.search);
  }
  onKeypressEvent(event: any) {
    console.log(event);
    let path = '';
    let queryParams;
    let allquery: any = {
      q: event,
    };
    this.router.navigate(['/search'], {
      queryParams: allquery,
      replaceUrl: true,
    });
  }
  if_login_change_showHeader_to_hide_header() {
    // console.log(this.location.path());
    // console.log(this.location.subscribe);
    if ('/login' == this.location.path()) {
      this.showHeader = false;
    }
  }

  ngOnInit(): void {
    this.if_login_change_showHeader_to_hide_header();
  }
}

<header class="site-header" style="
    display: grid;
    grid-template-columns: 1fr 1fr;
    align-items: center;
    justify-content: center;
    padding: 5px 8px;
  " *ngIf="showHeader">
  <div class="logo-and-tagline" *ngIf="showHeader" style="    text-align: center;">
    <a href="./" class="logo">
      <!-- <img class="logo-img" src="../../../assets//images//avatar.png" alt="ShopTalk Show Logo" style="width: 70px;"> -->
    </a>
    <a class="sr-only" href="./"> Alen Andry's Blog </a>
  </div>
  <div *ngIf="showHeader">
    <li class="main-nav-search" style="    display: flex;
    border: none;
    border-radius: 50%;
    text-align: center;
    margin: auto;
    align-items: unset;
    justify-content: center;">

      <input type="search" name="username" placeholder="search" [(ngModel)]="search" (change)="onChangeEvent($event)"
        (keyup.enter)="onChangeEvent($event)" (ngModelChange)="onKeypressEvent($event)" required />

      <a href="./search?q={{ search }}" class="jetpack-search-filter__link">
        <svg width="32" height="32" viewBox="0 0 32 32" fill="#463d38" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M15.0726 10.4326C12.4801 10.4326 10.4 12.5451 10.4 15.1053C10.4 17.6978 12.5125 19.7779 15.0726 19.7779C17.6651 19.7779 19.7453 17.6654 19.7453 15.1053C19.744 12.544 17.664 10.4326 15.0726 10.4326Z">
          </path>
          <path
            d="M16.0327 0.447479C7.42401 0.447479 0.447693 7.4238 0.447693 16.0324C0.447693 24.6398 7.42401 31.6161 16.0314 31.6161C24.64 31.6161 31.6163 24.6398 31.6163 16.0324C31.6163 7.4238 24.64 0.447479 16.0327 0.447479ZM23.6163 24.0324C23.3926 24.2562 23.0401 24.385 22.6563 24.385C22.2726 24.385 21.9526 24.2575 21.6963 24.0324L18.7526 21.0887L18.4651 21.2487C17.4088 21.825 16.2576 22.145 15.0724 22.145C11.1998 22.145 8.06509 19.0087 8.06509 15.1376C8.06509 11.265 11.2013 8.13023 15.0724 8.13023C18.9451 8.13023 22.0798 11.2665 22.0798 15.1376C22.0798 16.5138 21.6961 17.8251 20.9273 18.9776L20.7348 19.2976L23.6473 22.2101C23.8711 22.4664 24.0311 22.7864 24.0311 23.1376C23.9998 23.4563 23.8723 23.7763 23.616 24.0326L23.6163 24.0324Z">
          </path>
        </svg>
      </a>
    </li>
  </div>
</header>
<nav id="main-nav" class="main-nav mobile-is-closed" *ngIf="showHeader">
  <ul>
    <li class="main-nav-episodes"><a href="./rust">Rust Series</a></li>
    <li class="main-nav-series"><a href="./backend">Backend Series</a></li>
    <li class="main-nav-advertising">
      <a href="./fontend_ml">Frontend ML Series</a>
    </li>
    <li class="main-nav-ask"><a href="./javascript">javascript Series</a></li>
    <li class="main-nav-topics"><a href="./python">python Series</a></li>
    <li class="main-nav-topics"><a href="./java">Java Series</a></li>
    <li class="main-nav-ask"><a href="./vue">Vue Series</a></li>
    <li class="main-nav-ask"><a href="./react">React Series</a></li>
    <li class="main-nav-ask"><a href="./angular">Angular Series</a></li>
    <li class="main-nav-ask"><a href="./git">Git Series</a></li>
    <li class="main-nav-ask"><a href="./bash">Bash Series</a></li>
    <li class="main-nav-ask"><a href="./data_structure">Data Structure</a></li>
  </ul>
</nav>
